# Generated by Django 3.0.2 on 2020-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('done_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
