# Generated by Django 3.0.2 on 2020-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='done_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
